language: java
jdk:
  - oraclejdk8
services:
  - redis-server
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE questionnaire'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_question.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_servey.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_serveyResult.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_user.sql'
  - chmod +x gradlew
install:
  - ./gradlew assemble
script:
  - gradle check
