language: java
jdk:
  - oraclejdk8
services:
  - redis-server
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE questionnaire'
  - mysql -e 'source src/main/resources/sqlresource/*sql'
script:
  - gradle assemble
  - gradle check
