language: java
jdk:
  - oraclejdk8
services:
  - redis-server
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE questionnaire'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_question.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_servey.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_serveyResult.sql'
  - mysql -e 'use questionnaire source src/main/resources/sqlresource/questionnaire_user.sql'
install:
  - wget "https://services.gradle.org/distributions/gradle-5.0-bin.zip"
  - unzip -d /opt/gradle gradle-5.0-bin.zip
  - export PATH=$PATH:/opt/gradle/gradle-5.0/bin
  - gradle assemble
script:
  - gradle check
