logging:
  file: "questionnaire.log"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "eZi8V5E07aoARvy0"
    username: "questionnaire"
    url: "jdbc:mysql://173.82.232.134:3306/questionnaire"
  redis:
    host: "173.82.232.134"