logging:
  file: "questionnaire.log"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "eZi8V5E07aoARvy0"
    username: "questionnaire"
    url: "jdbc:mysql://173.82.232.134:3306/questionnaire"
  redis:
    host: "173.82.232.134"
  mail:
    host: "smtp.exmail.qq.com"
    password: "123456aA"
    username: "questionnaire@jieblog.cn"
    port: 465
    protocol: smtp
    test-connection: true
    properties: {"mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory"}