logging:
  file: "questionnaire.log"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${questionnaire_datasource_password}
    username: "questionnaire"
    url: ${questionnaire_datasource_url}
  redis:
    host: ${questionnaire_redis_host}
    password: ${questionnaire_redis_password}
  mail:
    host: ${questionnaire_mail_host}
    password: ${questionnaire_mail_password}
    username: ${questionnaire_mail_username}
    port: ${questionnaire_mail_port}
    protocol: smtp
    test-connection: true
    properties: {"mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory"}