package win.jieblog.questionnaire.model.entity;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String surveyserialid;
    /**
     * 问题
     */
    private String questionname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerA
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerB
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answerb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerC
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answerc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerD
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answerd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerE
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerF
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answerf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerG
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answerg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerAcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answeracount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerBcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answerbcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerCcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answerccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerDcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answerdcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerEcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answerecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerFcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answerfcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerGcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer answergcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionid
     *
     * @return the value of question.questionid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionid
     *
     * @param questionid the value for question.questionid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.surveyserialid
     *
     * @return the value of question.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getSurveyserialid() {
        return surveyserialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.surveyserialid
     *
     * @param surveyserialid the value for question.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setSurveyserialid(String surveyserialid) {
        this.surveyserialid = surveyserialid == null ? null : surveyserialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerA
     *
     * @return the value of question.answerA
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswera() {
        return answera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerA
     *
     * @param answera the value for question.answerA
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswera(String answera) {
        this.answera = answera == null ? null : answera.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerB
     *
     * @return the value of question.answerB
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswerb() {
        return answerb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerB
     *
     * @param answerb the value for question.answerB
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerb(String answerb) {
        this.answerb = answerb == null ? null : answerb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerC
     *
     * @return the value of question.answerC
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswerc() {
        return answerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerC
     *
     * @param answerc the value for question.answerC
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerc(String answerc) {
        this.answerc = answerc == null ? null : answerc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerD
     *
     * @return the value of question.answerD
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswerd() {
        return answerd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerD
     *
     * @param answerd the value for question.answerD
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerd(String answerd) {
        this.answerd = answerd == null ? null : answerd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerE
     *
     * @return the value of question.answerE
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswere() {
        return answere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerE
     *
     * @param answere the value for question.answerE
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswere(String answere) {
        this.answere = answere == null ? null : answere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerF
     *
     * @return the value of question.answerF
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswerf() {
        return answerf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerF
     *
     * @param answerf the value for question.answerF
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerf(String answerf) {
        this.answerf = answerf == null ? null : answerf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerG
     *
     * @return the value of question.answerG
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswerg() {
        return answerg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerG
     *
     * @param answerg the value for question.answerG
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerg(String answerg) {
        this.answerg = answerg == null ? null : answerg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerAcount
     *
     * @return the value of question.answerAcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnsweracount() {
        return answeracount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerAcount
     *
     * @param answeracount the value for question.answerAcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnsweracount(Integer answeracount) {
        this.answeracount = answeracount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerBcount
     *
     * @return the value of question.answerBcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswerbcount() {
        return answerbcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerBcount
     *
     * @param answerbcount the value for question.answerBcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerbcount(Integer answerbcount) {
        this.answerbcount = answerbcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerCcount
     *
     * @return the value of question.answerCcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswerccount() {
        return answerccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerCcount
     *
     * @param answerccount the value for question.answerCcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerccount(Integer answerccount) {
        this.answerccount = answerccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerDcount
     *
     * @return the value of question.answerDcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswerdcount() {
        return answerdcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerDcount
     *
     * @param answerdcount the value for question.answerDcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerdcount(Integer answerdcount) {
        this.answerdcount = answerdcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerEcount
     *
     * @return the value of question.answerEcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswerecount() {
        return answerecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerEcount
     *
     * @param answerecount the value for question.answerEcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerecount(Integer answerecount) {
        this.answerecount = answerecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerFcount
     *
     * @return the value of question.answerFcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswerfcount() {
        return answerfcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerFcount
     *
     * @param answerfcount the value for question.answerFcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswerfcount(Integer answerfcount) {
        this.answerfcount = answerfcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerGcount
     *
     * @return the value of question.answerGcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getAnswergcount() {
        return answergcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerGcount
     *
     * @param answergcount the value for question.answerGcount
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswergcount(Integer answergcount) {
        this.answergcount = answergcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.remark
     *
     * @return the value of question.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.remark
     *
     * @param remark the value for question.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createdatetime
     *
     * @return the value of question.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createdatetime
     *
     * @param createdatetime the value for question.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.updatedatetime
     *
     * @return the value of question.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.updatedatetime
     *
     * @param updatedatetime the value for question.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }

    public String getQuestionname() {
        return questionname;
    }

    public void setQuestionname(String questionname) {
        this.questionname = questionname;
    }
}