package win.jieblog.questionnaire.model.entity;

import java.util.Date;

public class ServeyResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.serveyresultid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer serveyresultid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.serveyresultserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String serveyresultserialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String surveyserialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.answererserialId
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answererserialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.answer
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.result
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serveyResult.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date updatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.serveyresultid
     *
     * @return the value of serveyResult.serveyresultid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getServeyresultid() {
        return serveyresultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.serveyresultid
     *
     * @param serveyresultid the value for serveyResult.serveyresultid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setServeyresultid(Integer serveyresultid) {
        this.serveyresultid = serveyresultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.serveyresultserialid
     *
     * @return the value of serveyResult.serveyresultserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getServeyresultserialid() {
        return serveyresultserialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.serveyresultserialid
     *
     * @param serveyresultserialid the value for serveyResult.serveyresultserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setServeyresultserialid(String serveyresultserialid) {
        this.serveyresultserialid = serveyresultserialid == null ? null : serveyresultserialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.surveyserialid
     *
     * @return the value of serveyResult.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getSurveyserialid() {
        return surveyserialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.surveyserialid
     *
     * @param surveyserialid the value for serveyResult.surveyserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setSurveyserialid(String surveyserialid) {
        this.surveyserialid = surveyserialid == null ? null : surveyserialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.answererserialId
     *
     * @return the value of serveyResult.answererserialId
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswererserialid() {
        return answererserialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.answererserialId
     *
     * @param answererserialid the value for serveyResult.answererserialId
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswererserialid(String answererserialid) {
        this.answererserialid = answererserialid == null ? null : answererserialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.answer
     *
     * @return the value of serveyResult.answer
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.answer
     *
     * @param answer the value for serveyResult.answer
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.result
     *
     * @return the value of serveyResult.result
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.result
     *
     * @param result the value for serveyResult.result
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.remark
     *
     * @return the value of serveyResult.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.remark
     *
     * @param remark the value for serveyResult.remark
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.createdatetime
     *
     * @return the value of serveyResult.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.createdatetime
     *
     * @param createdatetime the value for serveyResult.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serveyResult.updatedatetime
     *
     * @return the value of serveyResult.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serveyResult.updatedatetime
     *
     * @param updatedatetime the value for serveyResult.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }
}