package win.jieblog.questionnaire.model.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String userserialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    private Date updatedatetime;
    /**
     * 头像url
     */
    private String avatar;
    /**
     * 是否验证邮箱 0未验证 1已验证
     */
    private int isVerifiedEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userserialid
     *
     * @return the value of user.userserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getUserserialid() {
        return userserialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userserialid
     *
     * @param userserialid the value for user.userserialid
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUserserialid(String userserialid) {
        this.userserialid = userserialid == null ? null : userserialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createdatetime
     *
     * @return the value of user.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createdatetime
     *
     * @param createdatetime the value for user.createdatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updatedatetime
     *
     * @return the value of user.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updatedatetime
     *
     * @param updatedatetime the value for user.updatedatetime
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getIsVerifiedEmail() {
        return isVerifiedEmail;
    }

    public void setIsVerifiedEmail(int isVerifiedEmail) {
        this.isVerifiedEmail = isVerifiedEmail;
    }
}