package win.jieblog.questionnaire.dao;

import win.jieblog.questionnaire.model.entity.Question;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int deleteByPrimaryKey(Integer questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    Question selectByPrimaryKey(Integer questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKey(Question record);
}