package win.jieblog.questionnaire.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import win.jieblog.questionnaire.model.entity.Question;

import java.util.List;

@Mapper
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int deleteByPrimaryKey(Integer questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    Question selectByPrimaryKey(Integer questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKey(Question record);
    List<Question> selectByServeyserialid(@Param("serveyserialid") String serveyserialid);
}