package win.jieblog.questionnaire.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import win.jieblog.questionnaire.model.entity.Servey;

import java.util.List;
@Mapper
public interface ServeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int deleteByPrimaryKey(Integer serveyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insert(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insertSelective(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    Servey selectByPrimaryKey(Integer serveyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKey(Servey record);

    /**
     * 根据标题或标签模糊搜索 去除过期的问卷
     * @param keyword 关键字
     * @return
     */
    List<Servey> selectAllServeyByTagOrTitle(@Param("keyword") String keyword);
    Servey selectBySerialid(@Param("surveyserialid") String surveyserialid);
    int updateBySerialId(Servey  servey);
    List<Servey> selectMyServeyByTagOrTitle(@Param("userserialid") String userserialid,@Param("keyword") String keyword);
    List<Servey> selectMyAnswerServeyByTagOrTitle(@Param("list") List<String> list,@Param("keyword") String keyword);
}