package win.jieblog.questionnaire.dao;

import win.jieblog.questionnaire.model.entity.Servey;

public interface ServeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int deleteByPrimaryKey(Integer serveyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insert(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insertSelective(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    Servey selectByPrimaryKey(Integer serveyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(Servey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servey
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKey(Servey record);
}