package win.jieblog.questionnaire.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import win.jieblog.questionnaire.model.entity.ServeyResult;

import java.util.List;

@Mapper
public interface ServeyResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int deleteByPrimaryKey(Integer serveyresultid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insert(ServeyResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int insertSelective(ServeyResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    ServeyResult selectByPrimaryKey(Integer serveyresultid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(ServeyResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serveyResult
     *
     * @mbg.generated Thu Nov 15 15:45:15 CST 2018
     */
    int updateByPrimaryKey(ServeyResult record);
    List<ServeyResult> selectByAnswererserialId(@Param("answererserialId") String answererserialId);
}